version: '3.5'
services:
  peercoind:
    image: lorenz10/tempura:0.10.4
    restart: always
    environment:
      - RPC_USER=<USER>
      - RPC_PASSWORD=<PASSWORD>
    volumes:
      - type: bind
        source: ~/directory/tempura
        target: /data
    ports:
      - "9903:9903"
      - "9904:9904"
    command:
      -rpcbind=0.0.0.0/0
      -nominting
      -printtoconsole
      -testnet=1
  electrumx:
    image: lorenz10/electrumx:1.16.0
    environment:
      - DAEMON_URL=<USER>:<PASSWORD>@peercoind:9904
      - COIN=TempuraTestnet #added in my electrumx fork
      - NET=testnet
      - DB_DIRECTORY=/data
      - CACHE_MB=400
      - SERVICES=tcp://:50001,ssl://:50002,wss://:50004,rpc://0.0.0.0:8000
      - SSL_CERTFILE=/data/fullchain.pem
      - SSL_KEYFILE=/data/privkey.pem
    volumes:
      - type: bind
        source: ~/directory/db
        target: /data
    ports:
      - "50001:50001"
      - "50002:50002"
      - "50004:50004"
      - "8000:8000"
    restart: always
    depends_on:
      - peercoind #name of the process