version: '3.5'
services:
  peercoind:
    image: tempura
    restart: always
    environment:
      - RPC_USER=lore
      - RPC_PASSWORD=botti
    volumes:
      - type: bind
        source: /Users/lorenzobottini/electrum-data/peercoin
        target: /data
    ports:
      - "9903:9903"
      - "9904:9904"
    command:
      -rpcbind=0.0.0.0/0
      -nominting
      -printtoconsole
      -testnet=1
  electrumx:
    image: electrumx
    environment:
      - DAEMON_URL=lore:botti@peercoind
      - COIN=TempuraTestnet
      - DB_DIRECTORY=/data
      - CACHE_MB=400
      - SERVICES=tcp://:50001,ssl://:50002,wss://:50004,rpc://0.0.0.0:8000
    volumes:
      - type: bind
        source: /Users/lorenzobottini/electrum-data/db
        target: /data
    ports:
      - "50001:50001"
      - "50002:50002"
      - "50004:50004"
      - "8000:8000"
    restart: always
    depends_on:
      - peercoind